### ISSUE TITLE
MissingPluginException for only Android

### ISSUE THREAD

**Issue by PBomermustekiin** [flowmobile/storage_space#7]
/flutter (10070): error caught by report services: MissingPluginException(No implementation found for method getFreeSpace on channel storage_space)
I/flutter (10070): error: #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
I/flutter (10070): <asynchronous suspension>
I/flutter (10070): #1      _invokeMethodInt (package:photo_recovery_mobile/Core/Components/storage_space/storage_space.dart:75:16)
I/flutter (10070): <asynchronous suspension>
I/flutter (10070): #2      getStorageSpace (package:photo_recovery_mobile/Core/Components/storage_space/storage_space.dart:62:14)
I/flutter (10070): <asynchronous suspension>
I/flutter (10070): #3      GlobalController.getDeviceDiskSpace (package:photo_recovery_mobile/Core/Global/Controllers/global_controller.dart:150:33)
I/flutter (10070): <asynchronous suspension>
I/flutter (10070): #4      GlobalController.onInit (package:photo_recovery_mobile/Core/Global/Controllers/global_controller.dart:175:5)
I/flutter (10070): <asynchronous suspension>

**Comment by richanshah** [comment]
any updates?
